apiVersion: v1
kind: Pod
metadata:
  name: ui-preconfigs
  namespace: app-common-ui
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PostSync
  labels:
    app.kubernetes.io/name: ui-preconfigs
spec:
  containers:
  - name: myapp-container
    image: registry.access.redhat.com/ubi8/ubi
    command: ['bash', '-c', 'sleep 3 ; echo Modify UI config here']
    imagePullPolicy: Always
  restartPolicy: "Never"